apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-management.frontendName" . }}
  namespace: {{ include "employee-management.namespace" . }}
  labels:
    {{- include "employee-management.frontendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "employee-management.frontendName" . }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
