apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-management.postgresName" . }}
  namespace: {{ include "employee-management.namespace" . }}
  labels:
    {{- include "employee-management.postgresLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "employee-management.postgresName" . }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
