apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-management.name" . }}-secret
  namespace: {{ include "employee-management.namespace" . }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  FIRST_SUPERUSER: {{ .Values.secrets.firstSuperuser | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.secrets.firstSuperuserPassword | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  OBJECT_STORAGE_ACCESS_KEY: {{ .Values.secrets.objectStorageAccessKey | quote }}
  OBJECT_STORAGE_SECRET_KEY: {{ .Values.secrets.objectStorageSecretKey | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
