apiVersion: v1
kind: Service
metadata:
  name: employee-backend
  namespace: employee-management
  labels:
    app.kubernetes.io/name: employee-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: employee-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
