apiVersion: v1
kind: Secret
metadata:
  name: employee-management-secret
  namespace: employee-management
type: Opaque
stringData:
  SECRET_KEY: "dev-secret-key-change-me-please"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "Admin123!ChangeMe"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres-password-change-me"
  OBJECT_STORAGE_ACCESS_KEY: "employee-minio"
  OBJECT_STORAGE_SECRET_KEY: "employee-minio-secret"
  MINIO_ROOT_USER: "employee-minio"
  MINIO_ROOT_PASSWORD: "employee-minio-secret"
